<?php

namespace App\Http\Controllers;

use App\Http\Requests\DeviceToken\SendNotificationRequest;
use App\Http\Requests\DeviceToken\StoreDeviceTokenRequest;
use App\Http\Resources\DeviceTokenResource;
use App\Models\DeviceToken;
use App\Services\DeviceTokenService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Inertia\Inertia;

/**
 * @group Notifications
 *
 * Management of device tokens for push notifications (FCM).
 */
class DeviceTokenController extends Controller
{
    protected $tokenService;

    public function __construct(DeviceTokenService $tokenService)
    {
        $this->tokenService = $tokenService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $tokens = $this->tokenService->getAllTokens();

        if (request()->wantsJson()) {
            return DeviceTokenResource::collection($tokens);
        }

        return Inertia::render('DeviceTokens/Index', [
            'tokens' => DeviceTokenResource::collection($tokens)->resolve()
        ]);
    }

    /**
     * Register device token
     *
     * Registers or updates the FCM token for a device.
     * If the user is authenticated, the token will be linked to their account.
     *
     * @unauthenticated
     * @bodyParam fcm_token string required The token generated by Firebase. Example: eXp-123...
     * @bodyParam platform string The device platform (android, ios, web). Example: android
     */
    public function store(StoreDeviceTokenRequest $request)
    {
        $userId = Auth::guard('sanctum')->id() ?? $request->input('user_id');

        $deviceToken = $this->tokenService->updateOrCreateToken($request->validated(), $userId);

        return new DeviceTokenResource($deviceToken);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(DeviceToken $deviceToken)
    {
        $this->tokenService->deleteToken($deviceToken);

        if (request()->wantsJson()) {
            return response()->json(['status' => 'success']);
        }

        return redirect()->back()->with('success', 'Dispositivo eliminado correctamente.');
    }

    /**
     * Send a notification to the device.
     */
    public function sendNotification(SendNotificationRequest $request, DeviceToken $deviceToken)
    {
        try {
            $this->tokenService->sendNotification(
                $deviceToken,
                $request->title,
                $request->body,
                ['type' => $request->type]
            );

            if (request()->wantsJson()) {
                return response()->json([
                    'status' => 'success',
                    'message' => 'Notificación enviada correctamente.'
                ]);
            }

            return redirect()->back()->with('success', 'Notificación enviada correctamente.');
        } catch (\Exception $e) {
            if (request()->wantsJson()) {
                return response()->json([
                    'status' => 'error',
                    'message' => 'Error al enviar la notificación: ' . $e->getMessage()
                ], 500);
            }

            return redirect()->back()->withErrors(['error' => 'Error al enviar la notificación: ' . $e->getMessage()]);
        }
    }
}
